type EmojiInfos = {
  unicode: string
  nomPluriel: string
  nomSingulier: string
  articlePluriel: string
  articleSingulier: string
  articleCourt: string
}
export const listeEmojisInfos: Record<string, EmojiInfos> = {
  smiley: {
    unicode: '1f603',
    nomPluriel: 'smileys',
    nomSingulier: 'smiley',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  heart: {
    unicode: '2764',
    nomPluriel: 'cœurs',
    nomSingulier: 'cœur',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  thumbsUp: {
    unicode: '1f44d',
    nomPluriel: 'pouces levés',
    nomSingulier: 'pouce levé',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  étoile: {
    unicode: '2b50',
    nomPluriel: 'étoiles',
    nomSingulier: 'étoile',
    articlePluriel: 'les',
    articleSingulier: "l'",
    articleCourt: "d'",
  },
  pizza: {
    unicode: '1f355',
    nomPluriel: 'pizzas',
    nomSingulier: 'pizza',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  beer: {
    unicode: '1f37a',
    nomPluriel: 'bières',
    nomSingulier: 'bière',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  licorne: {
    unicode: '1f984',
    nomPluriel: 'licornes',
    nomSingulier: 'licorne',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  chien: {
    unicode: '1f436',
    nomPluriel: 'chiens',
    nomSingulier: 'chien',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  chat: {
    unicode: '1f431',
    nomPluriel: 'chats',
    nomSingulier: 'chat',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  souris: {
    unicode: '1f42d',
    nomPluriel: 'souris',
    nomSingulier: 'souris',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  tortue: {
    unicode: '1f422',
    nomPluriel: 'tortues',
    nomSingulier: 'tortue',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  pieuvre: {
    unicode: '1f419',
    nomPluriel: 'pieuvres',
    nomSingulier: 'pieuvre',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  poisson: {
    unicode: '1f41f',
    nomPluriel: 'poissons',
    nomSingulier: 'poisson',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  papillon: {
    unicode: '1f98b',
    nomPluriel: 'papillons',
    nomSingulier: 'papillon',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  fantome: {
    unicode: '1f47b',
    nomPluriel: 'fantômes',
    nomSingulier: 'fantôme',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  dragon: {
    unicode: '1f409',
    nomPluriel: 'dragons',
    nomSingulier: 'dragon',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  feu: {
    unicode: '1f525',
    nomPluriel: 'feux',
    nomSingulier: 'feu',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  fleur: {
    unicode: '1f33c',
    nomPluriel: 'fleurs',
    nomSingulier: 'fleur',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  etoileBrillante: {
    unicode: '1f31f',
    nomPluriel: 'étoiles brillantes',
    nomSingulier: 'étoile brillante',
    articlePluriel: 'les',
    articleSingulier: "l'",
    articleCourt: "d'",
  },
  cloche: {
    unicode: '1f514',
    nomPluriel: 'cloches',
    nomSingulier: 'cloche',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  crotte: {
    unicode: '1f4a9',
    nomPluriel: 'crottes',
    nomSingulier: 'crotte',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  fusee: {
    unicode: '1f680',
    nomPluriel: 'fusées',
    nomSingulier: 'fusée',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  drapeauDamier: {
    unicode: '1f3c1',
    nomPluriel: 'drapeaux damiers',
    nomSingulier: 'drapeau damier',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  arcEnCiel: {
    unicode: '1f308',
    nomPluriel: 'arcs-en-ciel',
    nomSingulier: 'arc-en-ciel',
    articlePluriel: 'les',
    articleSingulier: "l'",
    articleCourt: "d'",
  },
  soleil: {
    unicode: '2600',
    nomPluriel: 'soleils',
    nomSingulier: 'soleil',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  lune: {
    unicode: '1f319',
    nomPluriel: 'lunes',
    nomSingulier: 'lune',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  nuage: {
    unicode: '2601',
    nomPluriel: 'nuages',
    nomSingulier: 'nuage',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  cerise: {
    unicode: '1f352',
    nomPluriel: 'cerises',
    nomSingulier: 'cerise',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  pomme: {
    unicode: '1f34e',
    nomPluriel: 'pommes',
    nomSingulier: 'pomme',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  biere: {
    unicode: '1f37a',
    nomPluriel: 'bières',
    nomSingulier: 'bière',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  pingouin: {
    unicode: '1f427',
    nomPluriel: 'pingouins',
    nomSingulier: 'pingouin',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  banane: {
    unicode: '1f34c',
    nomPluriel: 'bananes',
    nomSingulier: 'banane',
    articlePluriel: 'les',
    articleSingulier: 'la',
    articleCourt: 'de',
  },
  fraise: {
    unicode: '1f353',
    nomPluriel: 'fraises',
    nomSingulier: 'fraise',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  raisin: {
    unicode: '1f347',
    nomPluriel: 'raisins',
    nomSingulier: 'raisin',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  pasteque: {
    unicode: '1f349',
    nomPluriel: 'pastèques',
    nomSingulier: 'pastèque',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  melon: {
    unicode: '1f348',
    nomPluriel: 'melons',
    nomSingulier: 'melon',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  orange: {
    unicode: '1f34a',
    nomPluriel: 'oranges',
    nomSingulier: 'orange',
    articlePluriel: 'les',
    articleSingulier: "l'",
    articleCourt: "d'",
  },
  citron: {
    unicode: '1f34b',
    nomPluriel: 'citrons',
    nomSingulier: 'citron',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  peche: {
    unicode: '1f351',
    nomPluriel: 'pêches',
    nomSingulier: 'pêche',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  poire: {
    unicode: '1f350',
    nomPluriel: 'poires',
    nomSingulier: 'poire',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  ananas: {
    unicode: '1f34d',
    nomPluriel: 'ananas',
    nomSingulier: 'ananas',
    articlePluriel: 'les',
    articleSingulier: "l'",
    articleCourt: "d'",
  },
  kiwi: {
    unicode: '1f95d',
    nomPluriel: 'kiwis',
    nomSingulier: 'kiwi',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
  mangue: {
    unicode: '1f96d',
    nomPluriel: 'mangues',
    nomSingulier: 'mangue',
    articlePluriel: 'les',
    articleSingulier: 'une',
    articleCourt: 'de',
  },
  explosion: {
    unicode: '1f4a5',
    nomPluriel: 'explosions',
    nomSingulier: 'explosion',
    articlePluriel: 'les',
    articleSingulier: "l'",
    articleCourt: "d'",
  },
  cadeau: {
    unicode: '1f381',
    nomPluriel: 'cadeaux',
    nomSingulier: 'cadeau',
    articlePluriel: 'les',
    articleSingulier: 'un',
    articleCourt: 'de',
  },
}
